### ISSUE TITLE
Nouvelles idees pour le climanifeste ?

### ISSUE THREAD

**Issue by jpic** [climanifeste/climanifeste#242]
Bonjour a toutes et a tous,

J'espere que vous allez bien.

Cette issue est une question concernant un elargissement du perimetre du climanifeste, pourquoi ne pas se positionner sur:

- les emballages a usage unique,
- la pollution au delas du CO2, notamment contre le deversement de dechets toxiques
- la deforestation massive incontrollée

D'autres idees peut etre ?

En vous souhaitant une agreable fin de journee

**Comment by climanifeste** [comment]
Bonjour et merci pour ces idées, mais le sujet du manifeste est la lutte contre le réchauffement climatique causé par l'activité humaine, et nous proposons pour cela une unique action à portée de tous les informaticien.ne.s. 

Dans nos métiers, quelles actions pourrions nous suggérer pour lutter contre les emballages ou la déforestation ?

**Comment by supertanuki** [comment]
Il faut voir ce manifeste comme un symbole. Inutile de l’alourdir sachant qu’il y a déjà 200 signataires et on ne peut pas leur redemander de résigner pour un texte étendu. L’idée est vraiment que chacun de son travail et son quotidien prenne conscience de ses actes et commence à agir en conséquence. Il ne s’agit plus seulement de trier ses déchets et supprimer ses e-mails. Il faut des actes plus impactant.

**Comment by jpic** [comment]
Je ne sais pas ou se situe la limite des "pros de l'informatique" faut il faire de la programmation ou du design toujours est il qu'il me semble que chaque emballage industrialo commercial a usage unique passe entre les mains d'un professionnel de l'informatique.
