### ISSUE TITLE
Ajouter courbe carbonne

### ISSUE THREAD

**Issue by jpic** [climanifeste/climanifeste#244]
Voici une courbe qui pourrait egalement etre presentee, pour dire en introduction que le taux de carbonne augmente stablement depuis les annees 60, maintenue par un groupe de hackers anglophone

https://carbon.datahub.io/?period=all
https://github.com/datopian/carbondoomsday

**Comment by climanifeste** [comment]
Merci pour cette proposition mais le but de ce manifeste n'est pas d'informer, mais de faire prendre conscience de la gravité et de l'urgence de la situation, ce à quoi cette courbe aiderait peu.

**Comment by jpic** [comment]
Cette courbe etait determinente en ce qui me concerne mais je dois etre un cas a part.

Merci pour votre reponse, bon week end a vous.
