### ISSUE TITLE
Spécification imprécise

### ISSUE THREAD

**Issue by gturri** [climanifeste/climanifeste#25]
Le terme `entreprises climaticides` est ambigü, et susceptible d'avoir des significations très différentes selon les personnes. Par exemple :
* une compagnie pétrolière est à coup sûr concernée
* mais une banque qui finance des compagnies pétrolières doit-elle aussi considérée ? Et si elle investi en parallèle dans la transition écologique ?
* est-ce que les compagnies d'aviation doivent être incluses ?
* et les agences de voyages (voire : airbnb), qui incitent, mais indirectement, à prendre l'avion ?

Bien sûr, la frontière est floue (c'est pourquoi je soumets un bug plutôt qu'une pull request). Mais plus elle le restera, et plus grand sera le risque que les rédacteurs du manifeste, les signataires, et les lecteurs, aient des interprétations très différentes de ses implications.

**Comment by jffourmond** [comment]
Merci @gturri, c'est une bonne remarque. Je suis d'accord avec toi, le terme est ambigü. 

Les entreprises que je qualifie de "climaticides" sont celles qui extraient les énergies fossiles et celles qui les financent. Il ne faut pas confondre les producteurs et les consommateurs. Une compagnie aérienne dépend des énergies fossiles certes, mais comme la quasi totalité des entreprises. Le tourisme mais aussi l'automobile et l'agro-alimentaire dépendent directement du pétrole. L'industrie dépend de centrales à charbon, énergie fossile aussi largement utilisée pour faire tourner les data centers américains. Bref, si on commence à pointer du doigt les entreprises consommatrices des énergies fossiles, on va vite finir par exclure tout le monde. Il vaut mieux réduire le problème à la source, c'est à dire du côté des producteurs.

Concernant les banques citées dans les liens du manifeste, tout dépend d'elles. Aujourd'hui, elles ne sont pas du bon côté. Comme le montre Oxfam dans son dernier rapport : "Entre 2016 et 2017, les banques ont réduit leurs financements à destination des énergies renouvelables, qui accusent un recul de 1,85 milliard d’euros en 2017 par rapport à 2016... alors que les financements vers les énergies fossiles augmentent dans le même temps d’un montant quasiment équivalent (+ 1,8 milliard d’euros) !". Difficile de parler de transition écologique dans ces conditions.

Pour revenir au terme "climaticides", que dirais-tu de préciser "les entreprises climaticides (voir liens en bas de page)" ou bien "les entreprises climaticides citées ci-dessous" par exemple ?

**Comment by gturri** [comment]
Est-ce "la faute" de celui qui produit l'offre ou de celui qui est à l'origine de la demande ? Débat vaste et non trivial...

> si on commence à pointer du doigt les entreprises consommatrices des énergies fossiles, on va vite finir par exclure tout le monde

Tout le monde, peut-être pas [1]... mais clairement, quand on voit par exemple les conclusions du rapport du shift project sur la sobriété numérique on réalise que certains pourront effectivement vouloir mettre le curseur assez loin [3].

Je n'aurais pas la prétention de pouvoir apporter des réponses (j'arrive à trouver des réponses qui me conviennent à peu près au niveau personnel, mais je me garderai bien de considérer qu'elles peuvent être universelles). Je crains juste de ne pouvoir m'engager à signer un manifeste dont je n'arrive pas à bien cerner les contours.

(j'ai bien conscience d'être dans la posture de l'utilisateur qui remonterait un bug tout en étant incapable d'expliquer quel est le comportement qu'il attendrait... n'hésite donc pas à fermer ce bug comme "incomplet" si tu préfères)

[1] : à l'extrême je pense à des sites comme https://donnons.org/ ou https://plus2vers.com/ dont la finalité justifie assez bien leur "pollution numérique". De manière moins caricaturale j'ai l'impression que plusieurs boites sont aussi "du bon côté" sans trop d'ambiguité.
[2] : https://theshiftproject.org/article/pour-une-sobriete-numerique-rapport-shift/
[3] : dans un sens, rien que de développer une app qui devient de plus en plus gourmande en ressources au fil des releases, c'est une manière de cautionner et de soutenir une forme d'obsolescence programmée

**Comment by jffourmond** [comment]
Pour moi, il est trop tard pour pour avoir ce débat. Il est nécessaire et urgent d'agir à tous les niveaux. Comme toi, j'agissais déjà individuellement en tant que consommateur [1]. Avec ce manifeste, on explore une piste pour mettre collectivement la pression sur les producteurs d'énergies fossiles. 

Pas de soucis pour le "bug", ça n'a aucune importance. La conversation reste ouverte. S'il te vient une idée pour modifier le texte du manifeste afin de permettre à plus de monde de s'y reconnaître, n'hésite pas !

[1] : https://github.com/jffourmond/ecologit

**Comment by supertanuki** [comment]
@gturri pour moi ce manifeste a valeur de symbole. On est conscient que ça va toucher principalement des gens acquis à cette cause. Mais si on arrive à faire réfléchir d'autres personnes dans l'IT, ça sera gagné. Que ce soit en bossant pour des boites climaticides ou pas.

**Comment by gturri** [comment]
> mettre collectivement la pression sur les producteurs d'énergies fossiles.

Je trouve que cette phrase est bien plus claire que celle du manifeste qui parle juste d'`entreprises climaticides`.
Du coup je pense qu'une manière de fermer ce bug serait de remplacer la phrase du manifeste par cette mention (ou éventuellement par une liste de secteurs à éviter)

**Comment by supertanuki** [comment]
aux entreprises productrices et celles qui les financent...

**Comment by climanifeste** [comment]
C'est déja précisé dans le paragraphe d'avant : 

> Face à l'urgence10, peut-on laisser les entreprises responsables du réchauffement climatique11 et celles qui les financent12, 13, 14, 15, 16, 17 agir sans conséquences ?

Je trouve que ça fait un peu lourd si on répète ça quelques lignes plus tard. 

Que diriez-vous de `pour signifier aux entreprises climaticides en question que nous refuserons dorénavant de travailler pour elles` ?

**Comment by jffourmond** [comment]
C'est déja précisé dans le paragraphe d'avant :

> Face à l'urgence10, peut-on laisser les entreprises responsables du réchauffement climatique11 et celles qui les financent12, 13, 14, 15, 16, 17 agir sans conséquences ?

Il suffit de cliquer sur lien [11] pour voir qu'il s'agit de producteurs d'énergies fossiles. 

Je trouve que ça fait un peu lourd si on répète ça quelques lignes plus tard.

Que diriez-vous de `pour signifier aux entreprises climaticides en question que nous refuserons dorénavant de travailler pour elles` ?

[11] https://www.forbes.fr/classements/100-entreprises-responsables-rechauffement-climatique/?cn-reloaded=1

**Comment by gturri** [comment]
ah, il fallait aller voir la note de bas de page ; effectivement, j'avais zappé ça, désolé...
Effectivement, déléguer à une source 3rd party le soin de déterminer les entreprises dans ce périmètre, c'est sûrement le meilleur choix ! 👍

**Comment by jffourmond** [comment]
J'ai réorganisé les 2 paragraphes sur les entreprises. Voici ma proposition : https://github.com/climanifeste/climanifeste/pull/37

Qu'est-ce que vous en pensez @gturri @guille-moe @DocRoms @sunny @supertanuki ?

**Comment by gturri** [comment]
Oui, ça me semble effectivement plus clair :+1:
