### ISSUE TITLE
Formulaire signataire

### ISSUE THREAD

**Issue by supertanuki** [climanifeste/climanifeste#5]
Je propose d'internaliser la gestion des signataires (pas de change.org ou autre). Faire un formulaire 
Prénom nom *, fonction *, url (site web, github, réseau social, et non requise) qui alimente une base firebase. On fait un petit script qui récupère cette info de Firebase, on le supprime de Firebase et on rajoute le signataire en dur dans la page des signataires. On peut faire tourner ce script tous les soirs manuellement ou automatiquement.

Ou on fait du low-tech on récupère manuellement de Firebase, mais comme on est des développeurs et les développeurs sont "fainéants"... :)

Ping @jffourmond

**Comment by jffourmond** [comment]
Je ne sais pas, je n'ai pas très envie de gérer des données personnelles, surtout maintenant que le RGPD est entré en vigueur. Si on fait un formulaire nous-mêmes, j'imagine qu'il faudra faire une déclaration à la CNIL, non ?

**Comment by supertanuki** [comment]
Oui mais tu ne stockes rien, tu les affiches directement. Faudrait se renseigner.
Après j'y penses, on peut demander aussi l'email à ceux qui le souhaitent pour recevoir un mailing d'information quant à la suite donnée à ce manifeste.

**Comment by jffourmond** [comment]
Si tu demandes un e-mail, il faudra bien le stocker, ça ne peut pas être une info visible.

**Comment by supertanuki** [comment]
oui bien sûr. Du coup ça remettrais en cause ce que je disais sur le fait de dropper la ligne de la bdd.

**Comment by supertanuki** [comment]
Après une déclaration simplifiée auprès de la cnil et les mentions qui vont bien, c'est pas compliqué.

**Comment by supertanuki** [comment]
Comme discuter par mail :
Finalement un site html statique et une page change.org ça peut être pas mal et ça demande pas beaucoup de travail, déclaration CNIL et de maintenance. Quant à l’hébergement du site statique, les pages github peuvent faire l’affaire ?

**Comment by supertanuki** [comment]
Donc on reste sur un format PR sur Github. On ferme ?

**Comment by jffourmond** [comment]
Yep. On reste sur les signatures par PR+mail et on mettra ça en forme via Github Pages.
